import { Background } from '@/components/svg/background'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AUdemy - Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className=' overflow-hidden  w-screen flex relative justify-center items-center h-screen bg-gradient-to-t from-purple-500 bg-black'>
      <Background />
      {children}
    </div>
  )
}
